const symbolGroups = [
['HIPPOUSDT_PERP.A,HFTUSDT_PERP.A,MAGICUSDT_PERP.A,MAVUSDT_PERP.A,ACEUSDT_PERP.A,SIRENUSDT_PERP.A,SYSUSDT_PERP.A,ATAUSDT_PERP.A,DEGOUSDT_PERP.A,DUSDT_PERP.A,BMTUSDT_PERP.A,NKNUSDT_PERP.A,AVAAIUSDT_PERP.A,SWARMSUSDT_PERP.A,NFPUSDT_PERP.A,THEUSDT_PERP.A,MBOXUSDT_PERP.A,LISTAUSDT_PERP.A,REZUSDT_PERP.A,ZEREBROUSDT_PERP.A'],
['TLMUSDT_PERP.A,SYNUSDT_PERP.A,GTCUSDT_PERP.A,FIDAUSDT_PERP.A,HOOKUSDT_PERP.A,PHBUSDT_PERP.A,SLERFUSDT_PERP.A,SWELLUSDT_PERP.A,HEIUSDT_PERP.A,RDNTUSDT_PERP.A,CHILLGUYUSDT_PERP.A,BRUSDT_PERP.A,1000RATSUSDT_PERP.A,VICUSDT_PERP.A,EPICUSDT_PERP.A,GHSTUSDT_PERP.A,REIUSDT_PERP.A,SANTOSUSDT_PERP.A,VINEUSDT_PERP.A,MAVIAUSDT_PERP.A'],
['PERPUSDT_PERP.A,LOKAUSDT_PERP.A,FLMUSDT_PERP.A,AVAUSDT_PERP.A,KOMAUSDT_PERP.A,QUICKUSDT_PERP.A,COSUSDT_PERP.A,JELLYJELLYUSDT_PERP.A,CHESSUSDT_PERP.A,VOXELUSDT_PERP.A,MYROUSDT_PERP.A,PIPPINUSDT_PERP.A,TOKENUSDT_PERP.A,TUTUSDT_PERP.A,FIOUSDT_PERP.A,BIDUSDT_PERP.A,RAYSOLUSDT_PERP.A,1000CHEEMSUSDT_PERP.A,BROCCOLIF3BUSDT_PERP.A,DEFIUSDT_PERP.A'],
['VELODROMEUSDT_PERP.A,1000XUSDT_PERP.A,1000WHYUSDT_PERP.A,1000CATUSDT_PERP.A,BROCCOLI714USDT_PERP.A,BTCDOMUSDT_PERP.A,FUNUSDT_PERP.A,MLNUSDT_PERP.A,GUNUSDT_PERP.A,ATHUSDT_PERP.A,BANKUSDT_PERP.A,WCTUSDT_PERP.A,SXTUSDT_PERP.A,AIOTUSDT_PERP.A,DOLOUSDT_PERP.A,HAEDALUSDT_PERP.A,PUNDIXUSDT_PERP.A,CTKUSDT_PERP.A,SIGNUSDT_PERP.A,JSTUSDT_PERP.A'],
['MEMEFIUSDT_PERP.A,INITUSDT_PERP.A,HYPERUSDT_PERP.A,BABYUSDT_PERP.A,PROMPTUSDT_PERP.A,XCNUSDT_PERP.A,FORTHUSDT_PERP.A,SAHARAUSDT_PERP.A,OLUSDT_PERP.A,BULLAUSDT_PERP.A,IDOLUSDT_PERP.A,MUSDT_PERP.A,MYXUSDT_PERP.A,FUSDT_PERP.A,NEWTUSDT_PERP.A,TAIKOUSDT_PERP.A,SQDUSDT_PERP.A,MERLUSDT_PERP.A,HYPEUSDT_PERP.A,PUFFERUSDT_PERP.A'],

];





module.exports = symbolGroups;

