const symbolGroups = [
['BSWUSDT_PERP.A,BONDUSDT_PERP.A,BELUSDT_PERP.A,AUCTIONUSDT_PERP.A,ATAUSDT_PERP.A,ASRUSDT_PERP.A,ALPINEUSDT_PERP.A,ALPACAUSDT_PERP.A,ADXUSDT_PERP.A,ACMUSDT_PERP.A,VIDTUSDT_PERP.A,VICUSDT_PERP.A,UTKUSDT_PERP.A,UNFIUSDT_PERP.A,TVKUSDT_PERP.A,TROYUSDT_PERP.A,TRBUSDT_PERP.A,TOKENUSDT_PERP.A,TKOUSDT_PERP.A,TKOUSDT_PERP.A'],
['SYNUSDT_PERP.A,SUIAUSDT_PERP.A,SFPUSDT_PERP.A,SANTOSUSDT_PERP.A,QUICKUSDT_PERP.A,QIUSDT_PERP.A,PROSUSDT_PERP.A,PORTOUSDT_PERP.A,POLSUSDT_PERP.A,PLAUSDT_PERP.A,PIVXUSDT_PERP.A,NTRNUSDT_PERP.A,NEXOUSDT_PERP.A,NEBLUSDT_PERP.A,MBOXUSDT_PERP.A,MAVIAUSDT_PERP.A,LTOUSDT_PERP.A,LOOMUSDT_PERP.A,KP3RUSDT_PERP.A,KMDUSDT_PERP.A'],
['JUVUSDT_PERP.A,JOEUSDT_PERP.A,IDEXUSDT_PERP.A,IDEXUSDT_PERP.A,GLMUSDT_PERP.A,GHSTUSDT_PERP.A,FRONTUSDT_PERP.A,FISUSDT_PERP.A,FETUSDT_PERP.A,ERNUSDT_PERP.A,ELFUSDT_PERP.A,DREPUSDT_PERP.A,DOCKUSDT_PERP.A,DGBUSDT_PERP.A,DEXEUSDT_PERP.A,DATAUSDT_PERP.A,COSUSDT_PERP.A,COMBOUSDT_PERP.A,CITYUSDT_PERP.A,CHESSUSDT_PERP.A'],
['CEEKUSDT_PERP.A,BURGERUSDT_PERP.A,BTSUSDT_PERP.A,BTCDOMUSDT_PERP.A,BTCSTUSDT_PERP.A,BLUEBIRDUSDT_PERP.A,BIFIUSDT_PERP.A,BETAUSDT_PERP.A,BELUSDT_PERP.A,BEAMUSDT_PERP.A,BARUSDT_PERP.A,BADGERUSDT_PERP.A,AUTOUSDT_PERP.A,ATMUSDT_PERP.A,ASTUSDT_PERP.A,API3USDT_PERP.A,ALPACAUSDT_PERP.A,AKROUSDT_PERP.A,AGLDUSDT_PERP.A,ADXUSDT_PERP.A'],
['ACHUSDT_PERP.A,1000BONKUSDT_PERP.A,1000FLOKIUSDT_PERP.A,1000LUNCUSDT_PERP.A,1000SHIBUSDT_PERP.A,1000XECUSDT_PERP.A,XAIUSDT_PERP.A,ZRXUSDT_PERP.A,YGGUSDT_PERP.A,XECUSDT_PERP.A,XCNUSDT_PERP.A,WUSDT_PERP.A,WAXUSDT_PERP.A,VTHOUSDT_PERP.A,VOXELUSDT_PERP.A,VITEUSDT_PERP.A,VANRYUSDT_PERP.A,USTCUSDT_PERP.A,USDCUSDT_PERP.A,TWTUSDT_PERP.A'],

];





module.exports = symbolGroups;

