const symbolGroups = [
['CTKUSDT_PERP.A, AIOTUSDT_PERP.A, DOLOUSDT_PERP.A, HAEDALUSDT_PERP.A, SXTUSDT_PERP.A, ASRUSDT_PERP.A, ALPINEUSDT_PERP.A, B2USDT_PERP.A, SYRUPUSDT_PERP.A, DOODUSDT_PERP.A, OGUSDT_PERP.A, SKYAIUSDT_PERP.A, NXPCUSDT_PERP.A, CVCUSDT_PERP.A, AGTUSDT_PERP.A, AWEUSDT_PERP.A, BUSDT_PERP.A, SOONUSDT_PERP.A, HUMAUSDT_PERP.A, AUSDT_PERP.A'],
['SOPHUSDT_PERP.A, MERLUSDT_PERP.A, HYPEUSDT_PERP.A, 1000000BOBUSDT_PERP.A, LAUSDT_PERP.A, HOMEUSDT_PERP.A, RESOLVUSDT_PERP.A, TAIKOUSDT_PERP.A, SQDUSDT_PERP.A, PUMPBTCUSDT_PERP.A, SPKUSDT_PERP.A, MYXUSDT_PERP.A, FUSDT_PERP.A, NEWTUSDT_PERP.A, HUSDT_PERP.A, SAHARAUSDT_PERP.A, ICNTUSDT_PERP.A, BULLAUSDT_PERP.A, IDOLUSDT_PERP.A, MUSDT_PERP.A'],
['PUMPUSDT_PERP.A, CROSSUSDT_PERP.A, AINUSDT_PERP.A, CUSDT_PERP.A, VELVETUSDT_PERP.A, TACUSDT_PERP.A, ERAUSDT_PERP.A, TAUSDT_PERP.A, CVXUSDT_PERP.A, SLPUSDT_PERP.A, ZORAUSDT_PERP.A, TAGUSDT_PERP.A, ESPORTSUSDT_PERP.A, TREEUSDT_PERP.A, PLAYUSDT_PERP.A, NAORISUSDT_PERP.A, TOWNSUSDT_PERP.A, PROVEUSDT_PERP.A, ALLUSDT_PERP.A, INUSDT_PERP.A'],
['CARVUSDT_PERP.A, AIOUSDT_PERP.A, XNYUSDT_PERP.A, USELESSUSDT_PERP.A, SAPIENUSDT_PERP.A, XPLUSDT_PERP.A, WLFIUSDT_PERP.A, SOMIUSDT_PERP.A, BASUSDT_PERP.A, BTRUSDT_PERP.A, MITOUSDT_PERP.A, HEMIUSDT_PERP.A, LINEAUSDT_PERP.A, QUSDT_PERP.A, ARIAUSDT_PERP.A, TAKEUSDT_PERP.A, PTBUSDT_PERP.A, OPENUSDT_PERP.A, FLOCKUSDT_PERP.A, SKYUSDT_PERP.A'],
['AVNTUSDT_PERP.A, HOLOUSDT_PERP.A, XPINUSDT_PERP.A, UBUSDT_PERP.A, ZKCUSDT_PERP.A, TOSHIUSDT_PERP.A, STBLUSDT_PERP.A, 0GUSDT_PERP.A, BARDUSDT_PERP.A, ASTERUSDT_PERP.A, TRADOORUSDT_PERP.A, BLESSUSDT_PERP.A, FLUIDUSDT_PERP.A, COAIUSDT_PERP.A, HANAUSDT_PERP.A, MIRAUSDT_PERP.A, AKEUSDT_PERP.A, ORDERUSDT_PERP.A, LIGHTUSDT_PERP.A, XANUSDT_PERP.A'],

];





module.exports = symbolGroups;

